dist: precise
language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
branches:
  only:
  - master
  - develop
before_script:
  - npm install
script:
  - npm run test:ci
  - npm run build